### ISSUE TITLE
g:fake_bootstrap not defined

### ISSUE THREAD

**Issue by okcompute** [tkhren/vim-fake#1]
Hi,

Found a small issue when adding to _fake_ definition through `fake#define` API. On Vim startup I get this error message:

```
Error detected while processing vim-fake/autoload/fake.vim: line  298:
E121: Undefined variable: g:fake_bootstrap
E116: Invalid arguments for function empty(g:fake_bootstrap)
E15: Invalid expression: !empty(g:fake_bootstrap)
Press ENTER or type command to continue
```

This is easily fixed by defining `g:fake_bootstrap` to an empty string in my .vimrc:

```
let g:fake_bootstrap=''
```

But this should probably be intialized within the plugin itself?

Thanks for this plugin!

**Comment by tkhren** [comment]
Fixed the bug. Thanks
